Delete private key
This was a mistake.

Report : 
ERROR: We're doing an SSH key audit.
Reason: unverified automatically (private key found in a public repository)
Please visit https://github.com/settings/keys/47408745
to approve this key so we know it's safe.

Fingerprint:
SHA256:UeF2KENjALaIDPVBdIR5eKGrNbVxJVmMcM6ZLW4nRcY

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists